version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: markvoronkov/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/app/collected_static/
      - media:/app/media/
    depends_on:
      - postgres

  frontend:
    image: markvoronkov/kittygram_frontend:latest
    command: >
      sh -c "cp -r /app/build/static/js /static/ &&
             cp -r /app/build/static/css /static/ &&
             cp -r /app/build/static/media /static/ 2>/dev/null || true &&
             cp /app/build/index.html
                /app/build/asset-manifest.json
                /app/build/manifest.json
                /app/build/robots.txt
                /app/build/favicon.ico
                /static/"
    volumes:
      - static:/static/
    depends_on:
      - backend

  gateway:
    image: markvoronkov/kittygram_gateway:latest
    volumes:
      - static:/static/
      - media:/media/
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend