volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: markvoronkov/kittygram_backend:latest
    env_file: .env
    volumes:
      - media:/app/media/
    depends_on:
      - postgres

  frontend:
    image: markvoronkov/kittygram_frontend:latest
    command: >
      sh -c "cp -r /app/build/static/. /static/ &&
             cp /app/build/index.html /static/ &&
             cp /app/build/asset-manifest.json /static/ &&
             cp /app/build/manifest.json /static/ &&
             cp /app/build/robots.txt /static/ &&
             cp /app/build/favicon.ico /static/"
    volumes:
      - static:/static/
    depends_on:
      - backend

  gateway:
    image: markvoronkov/kittygram_gateway:latest
    volumes:
      - static:/static/
      - media:/media/
    ports:
      - "9000:80"
    depends_on:
      - backend
      - frontend